### ISSUE TITLE
Suggestion: Campfire Logs Retain Original Wood Type

### ISSUE THREAD

**Issue by Jurklein** [spacegoat3/BuildableCampfire#10]
What if this mod actually overhauls the whole log-to-plank vanilla mechanics? It's very simple with what this mod already achieves:
- A log produces a campfire log - but the campfire log retains the wood type. For a first version, the block entity wouldn't have to be visually changed. In a second version, new sprites could be added.
- The campfire log produces planks of the original wood type. That's it! Nothing more!
- Bonus: instead of a stonecutter, the cutting mechanism could be achieved similarly to how the EarlyGame mod (https://www.curseforge.com/minecraft/mc-mods/earlygame) does it: to produce planks from logs, you can't do it anymore in the crafting table. Instead, you have to Shift+Click ontop of the log, which simulates the user actually cutting the log.

I'll reference the EarlyGame mod author here to help in ideas - and maybe on actual development!

**Comment by Jurklein** [comment]
@JayCeeCreates

**Comment by spacegoat3** [comment]
Thanks for this suggestion. I am actually working in an another mod that will have features like this to make Minecraft more realistic. This is a really nice idea and I would like to implement it to this new mod. If you want I can also credit you. 
Have a nice day :)

**Comment by Jurklein** [comment]
That would be nice!
What is the new mod? Does it have a public contribution page?

**Comment by spacegoat3** [comment]
It doesn't have a public page for now, sorry :/ 

I am still working on the mod's name. Its currently named as Primal but I am also thinking names like Evolution or Adaptation. I would love to have someone else's suggestion though. 
The new mod will be similar to the AlcatrazEscapee's famouse mod [No Tree Punching](https://github.com/alcatrazEscapee/no-tree-punching) but it will also have a lot more other features and that are both new and changes some of the game's already defined dynamics by using other mods.
  
For example, by using the Fabric Seasons mod, crops will no longer grow in Winter to make the game harder and make the player store food. 
Or campfires will need to be lit by hand using a Fire Striker until you can make a flint and they will have a time limit, and burn out if that ends unless you supply them with fuel.

These are just some of the ideas I have in my head. I know how to implement them, but it will sure take a long time to do so.

**Comment by Jurklein** [comment]
Primal is a good name, as it suggests to the reader the very core idea of the mod. I will, for sure, use it when it comes to life.

An obsevation/suggestion:
EarlyGame does the "no tree punching" process already; maybe focus on the other core ideas still not implemented by other mods? The campfire is a frustrating vanilla block; the design you proposed would make it much more interesting to incorporate in "Primal-related" modpacks! :-)

**Comment by spacegoat3** [comment]
Thanks for your suggestions :)
And sorry, I didn't clicked on the EarlyGame mod's page when I first read your post so I didn't realized that it already implemented the NTP features to the game. Thanks for pointing it out. 

I will continue developing the mod, and if you want I can make the GitHub Page public so you can follow the changes?

**Comment by Jurklein** [comment]
Yes, that would be great!
