### ISSUE TITLE
[Suggestion] Place first log on opposite side

### ISSUE THREAD

**Issue by BreadBxsket** [spacegoat3/BuildableCampfire#2]
Currently, the first log is always placed on the east, and the second is always placed on the west. For the second layer, towards the north first then the south second.

If possible, I'd like to be able to place the first log of each layer in the direction I am looking, mainly for improved usage as decoration instead of utility/immersion.

![2022-02-26_18 53 05](https://user-images.githubusercontent.com/30668741/155863026-0af9f78c-bee1-4964-9886-fa1a54d9f822.png)

I have this railway build I used to test out the mod. In it, I use the second-layer log to provide more coherence with the slab. Unfortunately with the way the mod functions, I can not place the first log facing the opposite direction. Not sure what it would take to make this change possible, but I hope it could be considered.

**Comment by spacegoat3** [comment]
Thank you for pointing this out, I will update and publish it right now.
