### ISSUE TITLE
Does not work with 1.18.2

### ISSUE THREAD

**Issue by realguyman** [spacegoat3/BuildableCampfire#3]
Currently your mod targets 1.18.1 as can be seen in your `gradle.properties` file. Nearly all mods built for 1.18.1 don't work for 1.18.2. That includes yours. This is an issue because **you've incorrectly labeled your mod as compatible with 1.18.2 on CurseForge releases when it is not.**

All of your mods that target 1.18.1 or 1.18.0 should be properly checked to see if they run on 1.18.2 (BuildableCampfire doesn't, the game crashes).

I would submit a crashlog, but it is pretty self explanatory why it isn't working.

Have a good day. :)

**Comment by spacegoat3** [comment]
Thank you for the warning. I haven't played Minecraft for nearly a month, so I didn't even knew there was a new version until today. I actually added the 1.18.2 version to the "fabric.mod.json" file but it seems like I forgot to rebuild it, so I probably just posted the old build. 

Thank you for the warning again and have a nice day :]
