### ISSUE TITLE
Add support for

### ISSUE THREAD

**Issue by TheButterbrotMan** [spacegoat3/BuildableCampfire#4]
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go

https://www.curseforge.com/minecraft/mc-mods/hyper-lighting-fabric

**Comment by spacegoat3** [comment]
Ok, I will try.

**Comment by spacegoat3** [comment]
I added support for the **Oh The Biomes You'll Go** but **Hyper Lightning** gives off an unknown error when combined with this mod, so I wasn't able to add support for it, sorry about that.
