### ISSUE TITLE
Crashes in Deathdusk modpack

### ISSUE THREAD

**Issue by TheButterbrotMan** [spacegoat3/BuildableCampfire#8]
The crash occurs whenever you right-click a campfire that is incomplete with the wrong item. REI does not show how to build a campfire this way, and neither do quests (as of 2.0.3, haven't booted up 2.0.4 yet) which means a player has to sift through the mod list to find out how to build a campfire (a key item for thirst management). Also, campfires logically come before a furnace  but, to craft a campfire you need smooth stone and iron ingots for a stone cutter, both of which comes from a furnace. Also, cutting wood on a stone-cutter is not sensible either.

https://bytebin.lucko.me/1n2XAKmHWR

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/60

**Comment by spacegoat3** [comment]
Ok, thanks  for the feedback. I will try to fix them as soon as possible.
